### ISSUE TITLE
Issue installing ppx_type_conv on opam with 4.03.0+flambda 

### ISSUE THREAD

**Issue by jgjl** [janestreet/ppx_type_conv#1]
Is ppx_type_conv supposed to work on 4.03.0+flambda?

Install ppx_type_conv with opam:

```
opam install ppx_type_conv
```

Error message:

```
cat ppx_type_conv-31471-d2c37b.err 
File "setup.ml", line 316, characters 20-36:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "setup.ml", line 316, characters 42-58:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "setup.ml", line 325, characters 14-30:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "setup.ml", line 325, characters 38-54:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "setup.ml", line 328, characters 25-41:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "setup.ml", line 366, characters 10-26:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "setup.ml", line 472, characters 13-29:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "setup.ml", line 1823, characters 16-33:
Warning 3: deprecated: String.capitalize
Use String.capitalize_ascii instead.
File "setup.ml", line 1829, characters 16-35:
Warning 3: deprecated: String.uncapitalize
Use String.uncapitalize_ascii instead.
File "setup.ml", line 5847, characters 11-28:
Warning 3: deprecated: String.capitalize
Use String.capitalize_ascii instead.
File "setup.ml", line 5848, characters 11-30:
Warning 3: deprecated: String.uncapitalize
Use String.uncapitalize_ascii instead.
W: Cannot find source file matching module 'ppx_type_conv' in library ppx_type_conv
E: Failure("Command ''/Users/user/.opam/4.03.0+flambda/bin/ocamlbuild' src/ppx_type_conv.cma src/ppx_type_conv.cmxa src/ppx_type_conv.a src/ppx_type_conv.cmxs ppx_deriving_exporter/ppx_type_conv_deriving.cma ppx_deriving_exporter/ppx_type_conv_deriving.cmxa ppx_deriving_exporter/ppx_type_conv_deriving.a ppx_deriving_exporter/ppx_type_conv_deriving.cmxs -use-ocamlfind -tag debug' terminated with error code 10")
make: *** [build] Error 1
 user@haruki-2  ~/.opam/4.03.0+flambda/build/ppx_type_conv.113.33.01+4.03  '/Users/user/.opam/4.03.0+flambda/bin/ocamlbuild' src/ppx_type_conv.cma src/ppx_type_conv.cmxa src/ppx_type_conv.a src/ppx_type_conv.cmxs ppx_deriving_exporter/ppx_type_conv_deriving.cma ppx_deriving_exporter/ppx_type_conv_deriving.cmxa ppx_deriving_exporter/ppx_type_conv_deriving.a ppx_deriving_exporter/ppx_type_conv_deriving.cmxs -use-ocamlfind -tag debug
Finished, 0 targets (0 cached) in 00:00:00.
```

When run manually:

```
+ /Users/user/.opam/4.03.0+flambda/bin/ocamlfind ocamlc -c -g -annot -bin-annot -no-alias-deps -thread -I src -package ppx_tools.metaquot -package ppx_driver -package ppx_deriving.api -package ppx_core -predicates ppx_driver -w -40 -I ppx_deriving_exporter -I src -o ppx_deriving_exporter/ppx_type_conv_deriving.cmo ppx_deriving_exporter/ppx_type_conv_deriving.ml
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /Users/user/.opam/4.03.0+flambda/lib/ocaml/compiler-libs, /Users/user/.opam/4.03.0+flambda/lib/ocaml
File "ppx_deriving_exporter/ppx_type_conv_deriving.ml", line 1, characters 62-74:
Error: Signature mismatch:
       ...
       Values do not match:
         val create :
           string ->
           ?core_type:(Parsetree.core_type -> Parsetree.expression) ->
           ?type_ext_str:(options:(string * Parsetree.expression) list ->
                          path:string list ->
                          Parsetree.type_extension -> Parsetree.structure) ->
           ?type_ext_sig:(options:(string * Parsetree.expression) list ->
                          path:string list ->
                          Parsetree.type_extension -> Parsetree.signature) ->
           ?type_decl_str:(options:(string * Parsetree.expression) list ->
                           path:string list ->
                           Parsetree.type_declaration list ->
                           Parsetree.structure) ->
           ?type_decl_sig:(options:(string * Parsetree.expression) list ->
                           path:string list ->
                           Parsetree.type_declaration list ->
                           Parsetree.signature) ->
           ?module_type_decl_str:(options:(string * Parsetree.expression)
                                          list ->
                                  path:string list ->
                                  Parsetree.module_type_declaration ->
                                  Parsetree.structure) ->
           ?module_type_decl_sig:(options:(string * Parsetree.expression)
                                          list ->
                                  path:string list ->
                                  Parsetree.module_type_declaration ->
                                  Parsetree.signature) ->
           unit -> deriver
       is not included in
         val create :
           string ->
           ?core_type:(Parsetree.core_type -> Parsetree.expression) ->
           ?type_ext_str:(Parsetree.structure, Parsetree.type_extension)
                         Ppx_type_conv.Std.Type_conv.Ppx_deriving_exporter.ppx_deriving_generator ->
           ?type_ext_sig:(Parsetree.signature, Parsetree.type_extension)
                         Ppx_type_conv.Std.Type_conv.Ppx_deriving_exporter.ppx_deriving_generator ->
           ?type_decl_str:(Parsetree.structure,
                           Parsetree.type_declaration list)
                          Ppx_type_conv.Std.Type_conv.Ppx_deriving_exporter.ppx_deriving_generator ->
           ?type_decl_sig:(Parsetree.signature,
                           Parsetree.type_declaration list)
                          Ppx_type_conv.Std.Type_conv.Ppx_deriving_exporter.ppx_deriving_generator ->
           unit -> deriver
Command exited with code 2.
Compilation unsuccessful after building 20 targets (19 cached) in 00:00:00.
```

opam switch

```
...
4.02.3          I 4.02.3          Official 4.02.3 release
--             -- 4.03.0          Official 4.03.0 release
4.03.0+flambda  C 4.03.0+flambda  Official 4.03.0 release with flambda activated
system          I system          System compiler (4.03.0)
```

**Comment by aganzha** [comment]
same here. was installing core on osx.

#=== ERROR while installing ppx_type_conv.113.33.01+4.03 ======================#

# opam-version 1.2.2

# os           darwin

# command      make

# path         /Users/aganzha/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03

# compiler     4.03.0

# exit-code    2

# env-file     /Users/aganzha/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-24565-d2c37b.env

# stdout-file  /Users/aganzha/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-24565-d2c37b.out

# stderr-file  /Users/aganzha/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-24565-d2c37b.err

### stdout

# Error: Signature mismatch:

# [...]

# unit -> deriver

# Command exited with code 2.

# \+ ocamlfind ocamlopt unix.cmxa -I /Users/aganzha/.opam/4.03.0/lib/ocamlbuild /Users/aganzha/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/aganzha/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild

# File "myocamlbuild.ml", line 518, characters 43-62:

# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize

# Use String.uncapitalize_ascii instead.

# File "myocamlbuild.ml", line 531, characters 51-70:

# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize

# Use String.uncapitalize_ascii instead.

### stderr

# [...]

# Use String.uncapitalize_ascii instead.

# File "setup.ml", line 5847, characters 11-28:

# Warning 3: deprecated: String.capitalize

# Use String.capitalize_ascii instead.

# File "setup.ml", line 5848, characters 11-30:

# Warning 3: deprecated: String.uncapitalize

# Use String.uncapitalize_ascii instead.

# W: Cannot find source file matching module 'ppx_type_conv' in library ppx_type_conv

# E: Failure("Command ''/Users/aganzha/.opam/4.03.0/bin/ocamlbuild' src/ppx_type_conv.cma src/ppx_type_conv.cmxa src/ppx_type_conv.a src/ppx_type_conv.cmxs ppx_deriving_exporter/ppx_type_conv_deriving.cma ppx_deriving_exporter/ppx_type_conv_deriving.cmxa ppx_deriving_exporter/ppx_type_conv_deriving.a ppx_deriving_exporter/ppx_type_conv_deriving.cmxs -use-ocamlfind -tag debug' terminated with error code 10")

# make: **\* [build] Error 1

Mac:~ aganzha$ ls /Users/aganzha/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/src/
META                ppx_type_conv.mldylib       std.ml
ignore_unused_warning.ml    ppx_type_conv.mllib     type_conv.ml
ignore_unused_warning.mli   ppx_type_conv.mlpack        type_conv.mli

**Comment by coolmenu** [comment]
Error in ubuntu 14.04 
ocaml 4.03

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ppx_type_conv failed at "make".

#=== ERROR while installing ppx_type_conv.113.33.01+4.03 ======================#

# opam-version 1.2.2

# os           linux

# command      make

# path         /home/ubuntu/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03

# compiler     4.03.0

# exit-code    2

# env-file     /home/ubuntu/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-18012-335865.env

# stdout-file  /home/ubuntu/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-18012-335865.out

# stderr-file  /home/ubuntu/.opam/4.03.0/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-18012-335865.err

### stdout

# Error: Signature mismatch:

# [...]

# unit -> deriver

# Command exited with code 2.

# \+ ocamlfind ocamlopt unix.cmxa -I /home/ubuntu/.opam/4.03.0/lib/ocamlbuild /home/ubuntu/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /home/ubuntu/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild

# File "myocamlbuild.ml", line 518, characters 43-62:

# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize

# Use String.uncapitalize_ascii instead.

# File "myocamlbuild.ml", line 531, characters 51-70:

# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize

# Use String.uncapitalize_ascii instead.

### stderr

# [...]

# Use String.uncapitalize_ascii instead.

# File "setup.ml", line 5847, characters 11-28:

# Warning 3: deprecated: String.capitalize

# Use String.capitalize_ascii instead.

# File "setup.ml", line 5848, characters 11-30:

# Warning 3: deprecated: String.uncapitalize

# Use String.uncapitalize_ascii instead.

# W: Cannot find source file matching module 'ppx_type_conv' in library ppx_type_conv

# E: Failure("Command ''/home/ubuntu/.opam/4.03.0/bin/ocamlbuild' src/ppx_type_conv.cma src/ppx_type_conv.cmxa src/ppx_type_conv.a src/ppx_type_conv.cmxs ppx_deriving_exporter/ppx_type_conv_deriving.cma ppx_deriving_exporter/ppx_type_conv_deriving.cmxa ppx_deriving_exporter/ppx_type_conv_deriving.a ppx_deriving_exporter/ppx_type_conv_deriving.cmxs -use-ocamlfind -tag debug' terminated with error code 10")

# make: **\* [build] Error 1

**Comment by alinpopa** [comment]
Same for me, on os x:

```
~ % opam install ppx_type_conv
The following actions will be performed:
  ∗  install ppx_type_conv 113.33.01+4.03

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ppx_type_conv] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of ppx_type_conv failed at "make".

#=== ERROR while installing ppx_type_conv.113.33.01+4.03 ======================#
# opam-version 1.2.2
# os           darwin
# command      make
# path         /Users/alin/.opam/system/build/ppx_type_conv.113.33.01+4.03
# compiler     system (4.03.0)
# exit-code    2
# env-file     /Users/alin/.opam/system/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-67492-e7966f.env
# stdout-file  /Users/alin/.opam/system/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-67492-e7966f.out
# stderr-file  /Users/alin/.opam/system/build/ppx_type_conv.113.33.01+4.03/ppx_type_conv-67492-e7966f.err
### stdout ###
# Error: Signature mismatch:
# [...]
#            unit -> deriver
# Command exited with code 2.
# + ocamlfind ocamlopt unix.cmxa -I /Users/alin/.opam/system/lib/ocamlbuild /Users/alin/.opam/system/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/alin/.opam/system/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "myocamlbuild.ml", line 518, characters 43-62:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
# File "myocamlbuild.ml", line 531, characters 51-70:
# Warning 3: deprecated: Ocamlbuild_plugin.String.uncapitalize
# Use String.uncapitalize_ascii instead.
### stderr ###
# [...]
# Use String.uncapitalize_ascii instead.
# File "setup.ml", line 5847, characters 11-28:
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# File "setup.ml", line 5848, characters 11-30:
# Warning 3: deprecated: String.uncapitalize
# Use String.uncapitalize_ascii instead.
# W: Cannot find source file matching module 'ppx_type_conv' in library ppx_type_conv
# E: Failure("Command ''/Users/alin/.opam/system/bin/ocamlbuild' src/ppx_type_conv.cma src/ppx_type_conv.cmxa src/ppx_type_conv.a src/ppx_type_conv.cmxs ppx_deriving_exporter/ppx_type_conv_deriving.cma ppx_deriving_exporter/ppx_type_conv_deriving.cmxa ppx_deriving_exporter/ppx_type_conv_deriving.a ppx_deriving_exporter/ppx_type_conv_deriving.cmxs -use-ocamlfind -tag debug' terminated with error code 10")
# make: *** [build] Error 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install ppx_type_conv 113.33.01+4.03
No changes have been performed
```

**Comment by dcorking** [comment]
Same error messages with Official 4.03.0 release. The workaround I used is `opam switch 4.02.3` in the shell.

I am not sure if this is an issue for ppx_type_conv or for opam. Should the error message indicate that the package is incompatible with 4.03, instead of failing to build?

```
available: [ ocaml-version = "4.02.3" ]
```

[opam file line 22](https://github.com/janestreet/ppx_type_conv/blob/master/opam#L22)

**Comment by alinpopa** [comment]
I did that "workaround" as well, although not considering an workaround, but more like an acceptable working env, as I need core which can't build because of this issue.

**Comment by lpw25** [comment]
A new backwards incompatible version of `ppx_deriving` was released last week. The constraints on `ppx_type_conv` in the opam repository need to have an upper bound added. In the meantime `opam install ppx_deriving.3.3` should fix things.

**Comment by lpw25** [comment]
In fact it has [already been fixed in the repository](https://github.com/ocaml/opam-repository/commit/c0d67110017a64b08081cab2e377872e8626e9a8), so an `opam update` should do the trick.

**Comment by Freyr666** [comment]
I'm still having an error while trying to install core:

[ERROR] The compilation of ppx_type_conv failed at "make".

http://pastebin.com/nSGQGHg3

**Comment by meadofpoetry** [comment]
I'm still getting an error while trying to install core:

[ERROR] The compilation of ppx_type_conv failed at "make"

http://pastebin.com/RGDgVF6J

**Comment by lpw25** [comment]
The repository only updated the dependencies on the latest ppx_type_conv. You're probably installing the older version of ppx_type_conv and still installing the backwards incompatible ppx_deriving 4.0.

**Comment by meadofpoetry** [comment]
> older version of ppx_type_conv

Can i specify the version of ppx_deriving or ppx_type_conv manually and what version should a specify? Thank you.

**Comment by lpw25** [comment]
Yeah, `opam install ppx_deriving.3.3 ppx_type_conv` should get you the right version of `ppx_deriving` and the latest version of `ppx_type_conv`.

**Comment by aganzha** [comment]
opam install ppx_deriving.3.3 ppx_type_conv  
worked, thank you
